package cn.edu.xmu.other.model.po;

import java.time.LocalDateTime;

public class AdvertisementPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.seg_id
     *
     * @mbg.generated
     */
    private Long segId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.begin_date
     *
     * @mbg.generated
     */
    private LocalDateTime beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.end_date
     *
     * @mbg.generated
     */
    private LocalDateTime endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.repeat
     *
     * @mbg.generated
     */
    private Byte repeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_advertisement.be_default
     *
     * @mbg.generated
     */
    private Byte beDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.id
     *
     * @return the value of other_advertisement.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.id
     *
     * @param id the value for other_advertisement.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.seg_id
     *
     * @return the value of other_advertisement.seg_id
     *
     * @mbg.generated
     */
    public Long getSegId() {
        return segId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.seg_id
     *
     * @param segId the value for other_advertisement.seg_id
     *
     * @mbg.generated
     */
    public void setSegId(Long segId) {
        this.segId = segId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.link
     *
     * @return the value of other_advertisement.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.link
     *
     * @param link the value for other_advertisement.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.content
     *
     * @return the value of other_advertisement.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.content
     *
     * @param content the value for other_advertisement.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.image_url
     *
     * @return the value of other_advertisement.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.image_url
     *
     * @param imageUrl the value for other_advertisement.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.state
     *
     * @return the value of other_advertisement.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.state
     *
     * @param state the value for other_advertisement.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.weight
     *
     * @return the value of other_advertisement.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.weight
     *
     * @param weight the value for other_advertisement.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.begin_date
     *
     * @return the value of other_advertisement.begin_date
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.begin_date
     *
     * @param beginDate the value for other_advertisement.begin_date
     *
     * @mbg.generated
     */
    public void setBeginDate(LocalDateTime beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.end_date
     *
     * @return the value of other_advertisement.end_date
     *
     * @mbg.generated
     */
    public LocalDateTime getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.end_date
     *
     * @param endDate the value for other_advertisement.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.repeat
     *
     * @return the value of other_advertisement.repeat
     *
     * @mbg.generated
     */
    public Byte getRepeat() {
        return repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.repeat
     *
     * @param repeat the value for other_advertisement.repeat
     *
     * @mbg.generated
     */
    public void setRepeat(Byte repeat) {
        this.repeat = repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.message
     *
     * @return the value of other_advertisement.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.message
     *
     * @param message the value for other_advertisement.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_advertisement.be_default
     *
     * @return the value of other_advertisement.be_default
     *
     * @mbg.generated
     */
    public Byte getBeDefault() {
        return beDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_advertisement.be_default
     *
     * @param beDefault the value for other_advertisement.be_default
     *
     * @mbg.generated
     */
    public void setBeDefault(Byte beDefault) {
        this.beDefault = beDefault;
    }
}