package cn.edu.xmu.other.model.po;

public class BeSharePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.goods_spu_id
     *
     * @mbg.generated
     */
    private Long goodsSpuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.sharer_id
     *
     * @mbg.generated
     */
    private Long sharerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.share_id
     *
     * @mbg.generated
     */
    private Long shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.order_item_id
     *
     * @mbg.generated
     */
    private Long orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_be_share.rebate
     *
     * @mbg.generated
     */
    private Integer rebate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.id
     *
     * @return the value of other_be_share.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.id
     *
     * @param id the value for other_be_share.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.goods_spu_id
     *
     * @return the value of other_be_share.goods_spu_id
     *
     * @mbg.generated
     */
    public Long getGoodsSpuId() {
        return goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.goods_spu_id
     *
     * @param goodsSpuId the value for other_be_share.goods_spu_id
     *
     * @mbg.generated
     */
    public void setGoodsSpuId(Long goodsSpuId) {
        this.goodsSpuId = goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.sharer_id
     *
     * @return the value of other_be_share.sharer_id
     *
     * @mbg.generated
     */
    public Long getSharerId() {
        return sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.sharer_id
     *
     * @param sharerId the value for other_be_share.sharer_id
     *
     * @mbg.generated
     */
    public void setSharerId(Long sharerId) {
        this.sharerId = sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.share_id
     *
     * @return the value of other_be_share.share_id
     *
     * @mbg.generated
     */
    public Long getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.share_id
     *
     * @param shareId the value for other_be_share.share_id
     *
     * @mbg.generated
     */
    public void setShareId(Long shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.customer_id
     *
     * @return the value of other_be_share.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.customer_id
     *
     * @param customerId the value for other_be_share.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.order_item_id
     *
     * @return the value of other_be_share.order_item_id
     *
     * @mbg.generated
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.order_item_id
     *
     * @param orderItemId the value for other_be_share.order_item_id
     *
     * @mbg.generated
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_be_share.rebate
     *
     * @return the value of other_be_share.rebate
     *
     * @mbg.generated
     */
    public Integer getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_be_share.rebate
     *
     * @param rebate the value for other_be_share.rebate
     *
     * @mbg.generated
     */
    public void setRebate(Integer rebate) {
        this.rebate = rebate;
    }
}