package cn.edu.xmu.other.model.po;

import java.time.LocalDateTime;

public class BeSharePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.goods_spu_id
     *
     * @mbg.generated
     */
    private Long goodsSpuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.sharer_id
     *
     * @mbg.generated
     */
    private Long sharerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.share_id
     *
     * @mbg.generated
     */
    private Long shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.order_item_id
     *
     * @mbg.generated
     */
    private Long orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.rebate
     *
     * @mbg.generated
     */
    private Integer rebate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_share.share_activity_id
     *
     * @mbg.generated
     */
    private Long shareActivityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.id
     *
     * @return the value of be_share.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.id
     *
     * @param id the value for be_share.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.goods_spu_id
     *
     * @return the value of be_share.goods_spu_id
     *
     * @mbg.generated
     */
    public Long getGoodsSpuId() {
        return goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.goods_spu_id
     *
     * @param goodsSpuId the value for be_share.goods_spu_id
     *
     * @mbg.generated
     */
    public void setGoodsSpuId(Long goodsSpuId) {
        this.goodsSpuId = goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.sharer_id
     *
     * @return the value of be_share.sharer_id
     *
     * @mbg.generated
     */
    public Long getSharerId() {
        return sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.sharer_id
     *
     * @param sharerId the value for be_share.sharer_id
     *
     * @mbg.generated
     */
    public void setSharerId(Long sharerId) {
        this.sharerId = sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.share_id
     *
     * @return the value of be_share.share_id
     *
     * @mbg.generated
     */
    public Long getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.share_id
     *
     * @param shareId the value for be_share.share_id
     *
     * @mbg.generated
     */
    public void setShareId(Long shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.customer_id
     *
     * @return the value of be_share.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.customer_id
     *
     * @param customerId the value for be_share.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.order_item_id
     *
     * @return the value of be_share.order_item_id
     *
     * @mbg.generated
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.order_item_id
     *
     * @param orderItemId the value for be_share.order_item_id
     *
     * @mbg.generated
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.rebate
     *
     * @return the value of be_share.rebate
     *
     * @mbg.generated
     */
    public Integer getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.rebate
     *
     * @param rebate the value for be_share.rebate
     *
     * @mbg.generated
     */
    public void setRebate(Integer rebate) {
        this.rebate = rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.gmt_create
     *
     * @return the value of be_share.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.gmt_create
     *
     * @param gmtCreate the value for be_share.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.gmt_modified
     *
     * @return the value of be_share.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.gmt_modified
     *
     * @param gmtModified the value for be_share.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_share.share_activity_id
     *
     * @return the value of be_share.share_activity_id
     *
     * @mbg.generated
     */
    public Long getShareActivityId() {
        return shareActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_share.share_activity_id
     *
     * @param shareActivityId the value for be_share.share_activity_id
     *
     * @mbg.generated
     */
    public void setShareActivityId(Long shareActivityId) {
        this.shareActivityId = shareActivityId;
    }
}