package cn.edu.xmu.other.model.po;

public class FootPrintPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_foot_print.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_foot_print.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_foot_print.goods_spu_id
     *
     * @mbg.generated
     */
    private Long goodsSpuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_foot_print.id
     *
     * @return the value of other_foot_print.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_foot_print.id
     *
     * @param id the value for other_foot_print.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_foot_print.customer_id
     *
     * @return the value of other_foot_print.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_foot_print.customer_id
     *
     * @param customerId the value for other_foot_print.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_foot_print.goods_spu_id
     *
     * @return the value of other_foot_print.goods_spu_id
     *
     * @mbg.generated
     */
    public Long getGoodsSpuId() {
        return goodsSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_foot_print.goods_spu_id
     *
     * @param goodsSpuId the value for other_foot_print.goods_spu_id
     *
     * @mbg.generated
     */
    public void setGoodsSpuId(Long goodsSpuId) {
        this.goodsSpuId = goodsSpuId;
    }
}