package cn.edu.xmu.other.model.po;

import java.time.LocalDateTime;

public class FootPrintPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_print.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_print.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_print.goods_spu_id
     *
     * @mbg.generated
     */
    private Long goodsSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_print.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_print.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_print.id
     *
     * @return the value of foot_print.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_print.id
     *
     * @param id the value for foot_print.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_print.customer_id
     *
     * @return the value of foot_print.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_print.customer_id
     *
     * @param customerId the value for foot_print.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_print.goods_spu_id
     *
     * @return the value of foot_print.goods_spu_id
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_print.goods_spu_id
     *
     * @param goodsSpuId the value for foot_print.goods_spu_id
     *
     * @mbg.generated
     */
    public void setGoodsSkuId(Long goodsSpuId) {
        this.goodsSkuId = goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_print.gmt_create
     *
     * @return the value of foot_print.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_print.gmt_create
     *
     * @param gmtCreate the value for foot_print.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_print.gmt_modified
     *
     * @return the value of foot_print.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_print.gmt_modified
     *
     * @param gmtModified the value for foot_print.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Long getGoodsSkuId() {
        return goodsSkuId;
    }
}