package cn.edu.xmu.other.model.po;

public class RegionPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_region.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_region.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_region.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_region.postal_code
     *
     * @mbg.generated
     */
    private Long postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_region.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_region.id
     *
     * @return the value of other_region.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_region.id
     *
     * @param id the value for other_region.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_region.pid
     *
     * @return the value of other_region.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_region.pid
     *
     * @param pid the value for other_region.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_region.name
     *
     * @return the value of other_region.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_region.name
     *
     * @param name the value for other_region.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_region.postal_code
     *
     * @return the value of other_region.postal_code
     *
     * @mbg.generated
     */
    public Long getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_region.postal_code
     *
     * @param postalCode the value for other_region.postal_code
     *
     * @mbg.generated
     */
    public void setPostalCode(Long postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_region.state
     *
     * @return the value of other_region.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_region.state
     *
     * @param state the value for other_region.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}