package cn.edu.xmu.other.model.po;

public class ShoppingCartPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_shopping_cart.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_shopping_cart.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_shopping_cart.goods_sku_id
     *
     * @mbg.generated
     */
    private Long goodsSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_shopping_cart.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_shopping_cart.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_shopping_cart.id
     *
     * @return the value of other_shopping_cart.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_shopping_cart.id
     *
     * @param id the value for other_shopping_cart.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_shopping_cart.customer_id
     *
     * @return the value of other_shopping_cart.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_shopping_cart.customer_id
     *
     * @param customerId the value for other_shopping_cart.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_shopping_cart.goods_sku_id
     *
     * @return the value of other_shopping_cart.goods_sku_id
     *
     * @mbg.generated
     */
    public Long getGoodsSkuId() {
        return goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_shopping_cart.goods_sku_id
     *
     * @param goodsSkuId the value for other_shopping_cart.goods_sku_id
     *
     * @mbg.generated
     */
    public void setGoodsSkuId(Long goodsSkuId) {
        this.goodsSkuId = goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_shopping_cart.quantity
     *
     * @return the value of other_shopping_cart.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_shopping_cart.quantity
     *
     * @param quantity the value for other_shopping_cart.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_shopping_cart.price
     *
     * @return the value of other_shopping_cart.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_shopping_cart.price
     *
     * @param price the value for other_shopping_cart.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }
}