package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.AddressPo;
import cn.edu.xmu.other.model.po.AddressPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    long countByExample(AddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int deleteByExample(AddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int insert(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int insertSelective(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    List<AddressPo> selectByExample(AddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    AddressPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AddressPo record, @Param("example") AddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AddressPo record, @Param("example") AddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AddressPo record);
}