package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.AdvertisementPo;
import cn.edu.xmu.other.model.po.AdvertisementPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertisementPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    long countByExample(AdvertisementPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int deleteByExample(AdvertisementPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int insert(AdvertisementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int insertSelective(AdvertisementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    List<AdvertisementPo> selectByExample(AdvertisementPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    AdvertisementPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdvertisementPo record, @Param("example") AdvertisementPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdvertisementPo record, @Param("example") AdvertisementPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdvertisementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdvertisementPo record);
}