package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.AftersaleServicePo;
import cn.edu.xmu.other.model.po.AftersaleServicePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AftersaleServicePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    long countByExample(AftersaleServicePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int deleteByExample(AftersaleServicePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int insert(AftersaleServicePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int insertSelective(AftersaleServicePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    List<AftersaleServicePo> selectByExample(AftersaleServicePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    AftersaleServicePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AftersaleServicePo record, @Param("example") AftersaleServicePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AftersaleServicePo record, @Param("example") AftersaleServicePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AftersaleServicePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AftersaleServicePo record);
}