package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.BeSharePo;
import cn.edu.xmu.other.model.po.BeSharePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BeSharePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    long countByExample(BeSharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int deleteByExample(BeSharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int insert(BeSharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int insertSelective(BeSharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    List<BeSharePo> selectByExample(BeSharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    BeSharePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BeSharePo record, @Param("example") BeSharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BeSharePo record, @Param("example") BeSharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BeSharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BeSharePo record);
}