package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.FavouriteGoodsPo;
import cn.edu.xmu.other.model.po.FavouriteGoodsPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavouriteGoodsPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    long countByExample(FavouriteGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int deleteByExample(FavouriteGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int insert(FavouriteGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int insertSelective(FavouriteGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    List<FavouriteGoodsPo> selectByExample(FavouriteGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    FavouriteGoodsPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FavouriteGoodsPo record, @Param("example") FavouriteGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FavouriteGoodsPo record, @Param("example") FavouriteGoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FavouriteGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FavouriteGoodsPo record);
}