package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.SharePo;
import cn.edu.xmu.other.model.po.SharePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SharePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    long countByExample(SharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int deleteByExample(SharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int insert(SharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int insertSelective(SharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    List<SharePo> selectByExample(SharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    SharePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SharePo record, @Param("example") SharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SharePo record, @Param("example") SharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SharePo record);
}