package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.ShoppingCartPo;
import cn.edu.xmu.other.model.po.ShoppingCartPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingCartPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    long countByExample(ShoppingCartPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingCartPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int insert(ShoppingCartPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingCartPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    List<ShoppingCartPo> selectByExample(ShoppingCartPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    ShoppingCartPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingCartPo record, @Param("example") ShoppingCartPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingCartPo record, @Param("example") ShoppingCartPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingCartPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_shopping_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingCartPo record);
}