package cn.edu.xmu.other.mapper;

import cn.edu.xmu.other.model.po.TimeSegmentPo;
import cn.edu.xmu.other.model.po.TimeSegmentPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeSegmentPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    long countByExample(TimeSegmentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int deleteByExample(TimeSegmentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int insert(TimeSegmentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int insertSelective(TimeSegmentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    List<TimeSegmentPo> selectByExample(TimeSegmentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    TimeSegmentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TimeSegmentPo record, @Param("example") TimeSegmentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TimeSegmentPo record, @Param("example") TimeSegmentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimeSegmentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimeSegmentPo record);
}